# Netlify Configuration for ASTRAL_NOTES Production Deployment
# Comprehensive configuration for optimal performance and SEO

[build]
  command = "npm run stellar:build"
  publish = "dist"
  
  # Environment variables for build
  environment = { NODE_ENV = "production", VITE_APP_NAME = "ASTRAL_NOTES", VITE_APP_VERSION = "1.0.0" }

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

# Redirects and rewrites for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
# API proxy (if needed)
[[redirects]]
  from = "/api/*"
  to = "https://api.astralnotes.com/:splat"
  status = 200
  force = true

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https: wss:; media-src 'self'; object-src 'none'; child-src 'none'; worker-src 'self'; manifest-src 'self'"

# Cache headers for static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/manifest.json"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/service-worker.js"
  [headers.values]
    Cache-Control = "no-cache"

# PWA specific
[[headers]]
  for = "/manifest.json"
  [headers.values]
    Content-Type = "application/manifest+json"

# Preload critical resources
[[headers]]
  for = "/index.html"
  [headers.values]
    Link = "</assets/main.css>; rel=preload; as=style, </assets/main.js>; rel=preload; as=script"

# Edge functions (if using Netlify Edge Functions)
[functions]
  directory = "netlify/edge-functions"

# Forms (if using Netlify Forms)
[forms]
  spam_protection = true

# Large Media (for large assets)
[large_media]
  lfs = true

# Split testing (A/B testing)
[split_testing]
  enabled = false

# Dev settings
[dev]
  command = "npm run dev"
  port = 7891
  publish = "dist"
  autoLaunch = true

# Environment-specific settings
[context.production]
  command = "npm run stellar:build"
  
  [context.production.environment]
    NODE_ENV = "production"
    VITE_APP_ENV = "production"
    VITE_APP_DEBUG = "false"

[context.deploy-preview]
  command = "npm run stellar:build"
  
  [context.deploy-preview.environment]
    NODE_ENV = "production"
    VITE_APP_ENV = "preview"
    VITE_APP_DEBUG = "true"

[context.branch-deploy]
  command = "npm run stellar:build"
  
  [context.branch-deploy.environment]
    NODE_ENV = "production"
    VITE_APP_ENV = "staging"
    VITE_APP_DEBUG = "true"